name: Run penguin on everything
on:
  # Hack to let me rernu this by starring the repo ;) - @funkypenguin
  watch:
   types: [started]
   
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: ["master"]
    paths: [".github/workflows/*"]

env:
  GITHUB_PAGES_BRANCH: gh-pages
  HELM_CHARTS_SOURCE: "./penguin/repos"
  HELM_VERSION: 3.2.0
  GITHUB_PAGES_REPO: funkypenguins-geek-cookbook/charts
  GITHUB_USERNAME: funkypenguins-geek-cookbook

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:

    - name: Download latest build
      run: |
        curl \
        $(\
        curl -s https://github_actor:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/funkypenguins-geek-cookbook/penguin/actions/artifacts | \
        jq '. as $in | [.artifacts[].id] | max as $max | $in | .artifacts[] | select (.id == $max) | .archive_download_url' -r \
        ) \
        -u github_actor:${{ secrets.GITHUB_TOKEN }} -L | \
        python2 -c "import zipfile,sys,StringIO;zipfile.ZipFile(StringIO.StringIO(sys.stdin.read())).extractall(sys.argv[1] if len(sys.argv) == 2 else '.')" penguin
        
        
      # Blame github for the unreasonably long command
    - name: Run it!
      run: |
        cd penguin
        chmod +x ./penguin
        ./penguin render -u github_actor -t ${{ secrets.AUTOCHEF_TOKEN }} -w

    - name: Checkout charts repo
      uses: actions/checkout@v2
      with:    
        repository: ${{ env.GITHUB_PAGES_REPO }}
        ref: ${{ env.GITHUB_PAGES_BRANCH }}   
        path: to_publish

    - name: Lint and package charts
      run: |
        find "${{ env.HELM_CHARTS_SOURCE }}" -mindepth 4 -maxdepth 4 -type d | grep charts/ | while read chart; do
          if [ -f $chart/Chart.yaml ]; then
            echo ">>> helm lint $chart"
            helm lint "$chart"

            chart_name="`basename "$chart"`"
            echo ">>> helm package -d to_publish/$chart_name $chart"
            mkdir -p "to_publish/$chart_name"
            helm dep update $chart
            helm package -d "to_publish/$chart_name" "$chart"
          fi
        done
        helm repo index to_publish
        
    - name: Push without action
      run: |
        cd to_publish
        git add .
        git commit -m 'Update charts'
        git push "https://funkypenguin-autochef:${{ secrets.AUTOCHEF_TOKEN }}@github.com/${{ env.GITHUB_PAGES_REPO }}.git"
#        git push "${remote_repo}" HEAD:${INPUT_BRANCH} --follow-tags $_FORCE_OPTION $_TAGS;

#    - name: Push changes
#      uses: ad-m/github-push-action@master
##      with:
 #       github_token: ${{ secrets.AUTOCHEF_TOKEN }}
#        directory: to_publish
#        branch: ${{ env.GITHUB_PAGES_BRANCH }}
#        repository: ${{ env.GITHUB_PAGES_REPO }}
#      env:
#        GITHUB_ACTOR: funkypenguin-autochef
