name: Run penguin on everything
on:
  # Hack to let me rernu this by starring the repo ;) - @funkypenguin
  watch:
   types: [started]
   
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: ["master"]
    paths: [".github/workflows/*"]

jobs:
  stale:

    runs-on: ubuntu-latest


    steps:
    - name: Download latest build
      run: |
        curl \
        $(\
        curl -s https://github_actor:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/funkypenguins-geek-cookbook/penguin/actions/artifacts | \
        jq '. as $in | [.artifacts[].id] | max as $max | $in | .artifacts[] | select (.id == $max) | .archive_download_url' -r \
        ) \
        -u github_actor:${{ secrets.GITHUB_TOKEN }} -L | \
        python2 -c "import zipfile,sys,StringIO;zipfile.ZipFile(StringIO.StringIO(sys.stdin.read())).extractall(sys.argv[1] if len(sys.argv) == 2 else '.')" penguin
        
        
      # Blame github for the unreasonably long command
    - name: Run it!
      run: |
        cd penguin
        chmod +x ./penguin
        ./penguin render -u github_actor -t ${{ secrets.GITHUB_TOKEN }} -w
      
